### PR TITLE
Pass correct reference to transforms dir

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by xjamundx** [comment]
nice!

**Comment by pgilad** [comment]
I actually have made a lot of local changes... I can add a PR for it

**Comment by xjamundx** [comment]
Thanks @pgilad . It's super hard to find time for me to work on this project!

**Comment by pgilad** [comment]
I actually got it working pretty good, but have also made local changes here and to `escodegen`.

`escodegen` looks like a very not-maintained project.

**Comment by xjamundx** [comment]
Sadly that appears to be the case. I saw your comment on my escodegen issue...

**Pull request merged**
